#!/usr/bin/env bash

#Remove services
sudo gitlab-ctl uninstall &&

#Clean any data generated by usage of the package
sudo gitlab-ctl cleanse &&

#You may also want to remove any accounts you configured. To do so
sudo gitlab-ctl remove-accounts &&

#Then remove the package using
sudo dpkg -P gitlab-ee &&

sudo apt -y purge gitlab-ee &&

#Remove directory
sudo rm -R /opt/gitlab &&

sudo apt -y autoremove
